sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci:lib
- npm run build-ci:lib
before_deploy:
- cp README.md dist/rest/README.md
- cd dist/rest
deploy:
  provider: npm
  email: github@joost.io
  skip_cleanup: true
  api_key:
    secure: SGsQz5MR1Ttgt2NlAwESt2Fl3g5knyjPBM0K7Ac1t2h7aDKGJAdzCu12TwE2Q/4iVZQ+c40h8LVvX9topG51Fm2+IH8HENWDCLPBoJ3Ohh/ZfPIanXTsXaNSDFoK4Lnx0TdDqAKgj8YCpeKntBHnakpDZCS5QkzQNnng6pFotmEv7S2qyqZPNYZmHpW5IHuK3OdVpEHAxJRbGqa5773ug5pYd2DADi94YUf/MXnzOGT4+NBRaWn7worwWCYK783P+9P1+5/ZrWWzRYKo9+E4EEZlRGhFAuNqQUixR42c4ibOXu1z7uymi0zBnLjm8xS0z9YIiCo3jJSlOKHVIqB309ZLSqaeiiMtC5meN1sNX3JRubEGJDwR875deTKfSNdMDIvaJJIuezPidn7mB3WRCwrTFo7RXEX+2KcqTmdgS7BaW6UsZNZ5cCcYPf8l9gDQgI7XNvwx1emcINYwPWjM4bxc+qPchbcYh+aqdV96Oygu1tscuX2kmaeoDxDmAGRtjuib2PyNPHxljV9SJIyTLRJ+XF1L3JOEmWrchZIfl1SWDNYDTDm5QytkKI02Gn1EMgJqP7St2RnkHsjiiTwcIjuF5PEpwaUwlW45P4VDhS+8FeTUA1ahCqGDCgr8pdkBoLxpmRrlDpT+gPJp1PM2JER55DtFYQXP3Nm2C33P2Yc=
  on:
    tags: true
    repo: ngxp/rest
