# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: "rest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run test-ci:lib
      - run: npm run build-ci:lib
      - run: cp README.md dist/$PROJECT/README.md
      - uses: JS-DevTools/npm-publish@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/${{ env.PROJECT }}/package.json



